version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: terraform
    directory: "/tests/cross-account-associations"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: terraform
    directory: "/tests/resolver"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: terraform
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
